version: "3.9"
services:
  db:
    image: postgres:12.1
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5555:5432"
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "cd ../ && sh start.sh"
    image: server
    volumes: 
      - ./transcendence_app/.:/transcendence_app/
    depends_on: 
      - db
    ports:
      - "3000:3000"
